# What is NumPy?

NumPy (numerical python) is a Python library used for working with arrays. It can 

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# Why use NumPy?

In Python we have lists that are similar to arrays, but they are slower to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

## Create a numpy array


In [2]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print (type(np_baseball))

<class 'numpy.ndarray'>


In [1]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Iterate over items in an array 

In [3]:
for val in np.nditer(arr):
    print (val)

1
2
3
4
5


# Compare vectors using boolean logic

greater, less_equal, greater_equal, equal, not_equal

In [4]:
np.less([1, 2], [2, 2])


array([False, False])

In [5]:
np.greater([1, 2], [2, 2])

array([False, False])